name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - head
        # CRuby < 2.6 does not support macos-arm64, so test those on amd64 instead
        exclude:
          - { os: macos-latest, ruby: "2.5" }
        include:
          - { os: macos-13, ruby: "2.5" }
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
